name: Feature Branch CI

on:
  workflow_dispatch:
  push:
    branches-ignore:
      - main

jobs:
  fast-feedback:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version: '1.25'

      - name: Install golangci-lint
        run: |
          go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest

      - name: Lint
        #run: golangci-lint run
        run: echo "Linting skipped in feature branch CI for faster feedback. Run golangci-lint locally before pushing to main."

      - name: Unit tests
        run: go test ./...

      - name: Build check
        run: go build .